import Marque from '@/components/news/Marque';
import Footer from '@/components/shared/Footer';
import Navbar from '@/components/shared/Navbar';
import type { Metadata } from 'next';
import { Noto_Serif_Bengali } from 'next/font/google';
import './globals.css';

const notoSerifBengali = Noto_Serif_Bengali({
    variable: '--font-noto-serif',
    subsets: ['latin', 'bengali'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
    return (
        <html
            lang="en"
            data-theme="light"
            className={`${notoSerifBengali.className} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <div className='top-0 sticky bg-white z-50'>
                    <Navbar />
                    <Marque />
                </div>
                {children}
                <Footer />
            </body>
        </html>
    );
}
